import React from "react";

interface PreviewPricingLine {
    description: string;
    quantity: number;
    price: number;
}

interface PreviewClient {
    name: string;
    company?: string;
    email?: string;
    phone?: string;
}

interface ProposalPreviewProps {
    client: PreviewClient | null;
    proposalTitle: string;
    proposalDescription: string;
    pricingLines: PreviewPricingLine[];
}

export function ProposalPreview({
                                    client,
                                    proposalTitle,
                                    proposalDescription,
                                    pricingLines,
                                }: ProposalPreviewProps) {

    if (!client) {
        return (
            <div className="border-2 border-dashed rounded-lg p-12 text-center bg-muted/20">
                <p className="text-lg font-medium mb-2">Proposal Preview</p>
                <p className="text-sm text-muted-foreground">Select a client & deal to begin</p>
            </div>
        );
    }

    const total = pricingLines.reduce(
        (sum, l) => sum + l.quantity * l.price,
        0
    );

    return (
        <div className="bg-white shadow border rounded-lg p-8 space-y-6 text-sm leading-relaxed">

            {/* HEADER */}
            <div className="bg-blue-600 text-white text-center py-3 rounded">
                <h2 className="text-xl font-bold">Proposal Document</h2>
            </div>

            {/* CLIENT META */}
            <div className="flex justify-between text-sm mt-4">
                <div className="whitespace-pre-line">
                    <strong>{client.name}</strong><br />
                    {client.company && <>{client.company}<br /></>}
                    {client.email && <>{client.email}<br /></>}
                    {client.phone && <>{client.phone}<br /></>}
                </div>

                <div className="text-right whitespace-pre-line">
                    Proposal: {proposalTitle || "—"}<br />
                    Date: {new Date().toLocaleDateString()}
                </div>
            </div>

            {/* TITLE */}
            <h1 className="text-2xl font-bold">{proposalTitle || "Untitled Proposal"}</h1>

            {/* SUMMARY */}
            <Section title="Summary">
                <p>
                    {proposalDescription?.length
                        ? proposalDescription
                        : "A structured proposal outlining the agreed scope and pricing."}
                </p>
            </Section>

            {/* PRICING */}
            <Section title="Pricing">
                <table className="w-full text-left border border-gray-300 text-sm">
                    <thead className="bg-blue-600 text-white">
                    <tr>
                        <th className="p-2">Item</th>
                        <th className="p-2 w-16 text-center">Qty</th>
                        <th className="p-2 w-24 text-right">Price</th>
                    </tr>
                    </thead>
                    <tbody>
                    {pricingLines.map((l, i) => (
                        <tr key={i} className={i % 2 === 0 ? "bg-white" : "bg-gray-100"}>
                            <td className="p-2">{l.description || "—"}</td>
                            <td className="p-2 text-center">{l.quantity}</td>
                            <td className="p-2 text-right">€{l.price.toLocaleString()}</td>
                        </tr>
                    ))}
                    </tbody>
                </table>

                <div className="text-right text-lg font-bold mt-2">
                    Total: €{total.toLocaleString()}
                </div>
            </Section>

            {/* ACCEPTANCE */}
            <Section title="Acceptance">
                <p>If approved, reply with confirmation to proceed.</p>

                <div className="mt-4">
                    <p>Signature: __________________________</p>
                    <p>Date: __________________________</p>
                </div>
            </Section>

            {/* FOOTER */}
            <div className="text-center text-xs text-muted-foreground pt-4 border-t">
                Generated by ClientTrack — CodeBShift.dev
            </div>

        </div>
    );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
    return (
        <div className="space-y-2">
            <h3 className="text-lg font-bold">{title}</h3>
            <div>{children}</div>
        </div>
    );
}
